# Generated by Django 4.0.4 on 2022-05-09 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopters', '0002_alter_adopter_zipcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='adopter',
            name='pets',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='adopter',
            name='pets_age',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='adopter',
            name='pets_breed',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='adopter',
            name='pets_sex',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='adopter',
            name='pets_species',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='adopter',
            name='phone',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
