# Generated by Django 4.0.4 on 2022-05-10 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopters', '0003_adopter_pets_adopter_pets_age_adopter_pets_breed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adopter',
            name='adoption_date',
            field=models.DateField(null=True),
        ),
    ]
