# Generated by Django 4.0.4 on 2022-05-13 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adopters', '0004_adopter_adoption_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adopter',
            old_name='user',
            new_name='username',
        ),
    ]
