# Generated by Django 4.0.4 on 2022-05-13 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adopters', '0005_rename_user_adopter_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adopter',
            old_name='username',
            new_name='user',
        ),
    ]
