# Generated by Django 4.0.4 on 2022-05-13 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adopters', '0006_rename_username_adopter_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adopter',
            old_name='user',
            new_name='user_username',
        ),
    ]
