# Generated by Django 4.0.4 on 2022-05-16 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adopters', '0007_rename_user_adopter_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adopter',
            old_name='user_username',
            new_name='user',
        ),
    ]
