# Generated by Django 4.0.4 on 2022-05-03 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animals', '0001_initial'),
        ('adopters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalAdopter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adoption_date', models.DateField()),
                ('adopter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adopters.adopter')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.animal')),
            ],
        ),
    ]
