# Generated by Django 4.0.4 on 2022-05-10 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animal_adopters', '0002_animaladopter_adopter_first_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animaladopter',
            name='adopter_first_name',
        ),
    ]
